name: Build Arch Linux ARM RPi4 AArch64 Image

on:
  workflow_dispatch:
    inputs:
      disable_free_disk_space:
        description: 'Disable Free Disk Space (speeds up build)'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 0 */10 * *'

jobs:
  build:
    name: Build RPi4 AArch64 Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Free Disk Space (Ubuntu)
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.disable_free_disk_space != 'true')
        uses: jlumbroso/free-disk-space@v1.3.1
      
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            qemu-user-static \
            binfmt-support \
            parted \
            libarchive-tools \
            dosfstools \
            e2fsprogs \
            zstd \
            wget

      - name: Run script
        run: |
           chmod x+ ./scripts/build-image.sh
           ./scripts/build-image.sh
          
      - name: Upload Zstd-zipped Image
        uses: actions/upload-artifact@v4
        with:
          name: archlinuxarm-rpi4-aarch64-sdcard-zstd
          path: "*.img.zst"
          retention-days: 30
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.TIMESTAMP }}"
          name: "Arch Linux RPi4 AArch64 - ${{ env.TIMESTAMP }}"
          files: |
            *.img.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
